[package]
    authors = ["Joaquín Zúñiga"]
    edition = "2024"
    name    = "panic-man"
    version = "0.1.0"

[dependencies]
    clap         = { version = "4.5.52", features = ["derive"] }
    clap_builder = { version = "4.5.52", features = ["cargo"] }
