name: build release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          # - os: ubuntu-latest
          #   target: x86_64-unknown-linux-musl
          #   ext: ""
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          #   ext: ""
          # - os: macos-latest
          #   target: aarch64-apple-darwin
          #   ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: build
        run: cargo build --release --target ${{ matrix.target }}

      - name: package release
        shell: bash
        run: |
          mkdir -p dist

          EXT="${{ matrix.ext }}"
          TARGET="${{ matrix.target }}"

          BIN_NAME="panic-man"
          BIN_PATH="target/${TARGET}/release/${BIN_NAME}${EXT}"
          CHECKSUM="dist/${BIN_NAME}-${TARGET}.sha256"

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ARCHIVE="dist/${BIN_NAME}-${TARGET}.zip"
            powershell -Command "Compress-Archive -Path '${BIN_PATH}' -DestinationPath '${ARCHIVE}'"
          else
            ARCHIVE="dist/${BIN_NAME}-${TARGET}.tar.gz"
            tar czf "${ARCHIVE}" -C "target/${TARGET}/release" "${BIN_NAME}${EXT}"
          fi

          sha256sum $ARCHIVE > $CHECKSUM

      - name: upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: panic-man-${{ matrix.target }}
          path: dist/*
          if-no-files-found: error

  release:
    name: release build
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
